spring.application.name=queue-x-workers

server.port=8080

# =====================
# MYSQL
# =====================
spring.datasource.url=${WORKER_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =====================
# SQS
# =====================
queue.provider=sqs

aws.access.key=${AWS_ACCESS_KEY_ID}
aws.secret.key=${AWS_SECRET_ACCESS_KEY}

# SQS Queue URLs
sqs.url.order_queue=${SQS_ORDER_QUEUE_URL}
sqs.url.out_of_stock=${SQS_OUT_OF_STOCK_URL}
sqs.url.notification=${SQS_NOTIFICATION_URL}
sqs.url.payment_queue=${SQS_PAYMENT_QUEUE_URL}
sqs.url.payment_success_queue=${SQS_PAYMENT_SUCCESS_QUEUE_URL}
sqs.url.payment_failed_queue=${SQS_PAYMENT_FAILED_QUEUE_URL}
sqs.url.payment_failed_for_order_api_queue=${SQS_PAYMENT_FAILED_FOR_ORDER_API_QUEUE_URL}