package com.keyur.queue_x_workers.Enums;

public enum EventType {
    ORDER_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_SUCCESS_NOTIFICATION,
    INVENTORY_SUCCESS,
    OUT_OF_STOCK,
    OUT_OF_STOCK_NOTIFICATION,
    PAYMENT_FAILED,
    PAYMENT_FAILED_FOR_ORDER_API,
    PAYMENT_FAILED_NOTIFICATION
}
